### ISSUE TITLE
Incompatible with Composer v2

### ISSUE THREAD

**Issue by d8vjork** [aw-studio/fjord#31]
Hi there, I was trying to install a fresh Laravel 7 app (PHP 7.4.7, composer v2 tried also with 1.x) but the package returns  the mentioned on the title.

I was just gonna try this project but seems something's on the Fjord's own kind of package discover, full error:

```
[2020-06-18 12:54:23] local.ERROR: Undefined index: name {"exception":"[object] (ErrorException(code: 0): Undefined index: name at /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php:88)
[stacktrace]
#0 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php(88): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/d8vjork/...', 88, Array)
#1 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Support/Collection.php(685): Fjord\\Fjord\\Discover\\PackageDiscoverCommand->Fjord\\Fjord\\Discover\\{closure}(Array, 'packages')
#2 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php(89): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#3 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php(76): Fjord\\Fjord\\Discover\\PackageDiscoverCommand->filterFjordPackages(Array)
#4 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php(100): Fjord\\Fjord\\Discover\\PackageDiscoverCommand->findFjordPackages('/Users/d8vjork/...')
#5 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/aw-studio/fjord/src/Fjord/Discover/PackageDiscoverCommand.php(53): Fjord\\Fjord\\Discover\\PackageDiscoverCommand->build()
#6 [internal function]: Fjord\\Fjord\\Discover\\PackageDiscoverCommand->handle(Object(Illuminate\\Foundation\\PackageManifest))
#7 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#8 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#13 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Fjord\\Fjord\\Discover\\PackageDiscoverCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /Users/d8vjork/Projects/Testing/laravel-fjord-fresh/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
```

Steps followed in order from: https://www.fjord-admin.com/docs/getting-started/installation/#installing-fjord

**OS version:** Mac OS Catalina 10.15.5
**PHP version:** 7.4.7
**Laravel version:** 7.16.1
**Composer version:** 2.0.0-alpha1 2020-06-03 13:44:20 (Also tried v1.10.7)
**Fjord version:** 2.3.4

**Comment by d8vjork** [comment]
Ok no, the install with composer v1.x works

Composer 2.x modify the `vendor/composer/installed.json` to a different structure
